language: node_js
node_js: "node"

install:
  - npm install -g codecov
  - npm install

script:
  - npm run build
  - npm test -- --coverage
  - codecov

branches:
  only:
    - master
    - deploy

deploy:
  provider: s3
  access_key_id: $AWS_S3_ACCESS_KEY_ID
  secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
  bucket: "bills.martincostello.com"
  region: eu-west-2
  skip_cleanup: true
  local_dir: build
  detect_encoding: true
  on:
    branch: deploy
