dist: xenial
language: node_js
node_js: "node"

install:
  - npm install -g codecov
  - npm ci

script:
  - npm run build
  - npm test -- --coverage
  - codecov

branches:
  only:
    - master
    - deploy

deploy:
  - provider: s3
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    bucket: "bills.martincostello.com"
    region: eu-west-2
    skip_cleanup: true
    local_dir: build
    detect_encoding: true
    cache_control: "max-age=604800"
    on:
      branch: deploy
  - provider: lambda
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    region: "us-east-1"
    function_name: "bills-martincostello-com-response-headers"
    role: "arn:aws:iam::492538393790:role/service-role/lambda_basic_execution_cloudfront_edge"
    handler_name: "handler"
    module_name: "cloudfront"
    timeout: 1,
    runtime: "nodejs8.10"
    zip: "cloudfront.js"
    publish: true
    on:
      branch: deploy
