dist: bionic
language: csharp
mono: none

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - NUGET_XMLDOC_MODE=skip

script:
  - ./build.sh

branches:
  only:
    - master
    - deploy

deploy:
  - provider: s3
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    bucket: "bills.martincostello.com"
    region: eu-west-2
    skip_cleanup: true
    local_dir: "artifacts/publish/wwwroot"
    detect_encoding: true
    cache_control: "max-age=604800"
    on:
      branch: deploy
  - provider: lambda
    access_key_id: $AWS_S3_ACCESS_KEY_ID
    secret_access_key: $AWS_S3_SECRET_ACCESS_KEY
    region: "us-east-1"
    function_name: "bills-martincostello-com-response-headers"
    role: "arn:aws:iam::492538393790:role/service-role/lambda_basic_execution_cloudfront_edge"
    handler_name: "handler"
    module_name: "cloudfront"
    timeout: 1,
    runtime: "nodejs10.x"
    zip: "cloudfront.js"
    publish: true
    on:
      branch: deploy
