language: node_js
node_js: "node"

install:
  - npm install -g codecov
  - npm install

script:
  - npm run build
  - npm test -- --coverage
  - codecov

branches:
  only:
    - master
    - deploy

deploy:
  provider: s3
  access_key_id:
    secure: VvtT22wceicCPqTQtb9SJ4U6quJzn3Sjb8U3StNpI16TDjUlHnWgwOGHD6Y/QhZSyx9NdbTJno/q9h9QxiBNGtoa1tUnEuaaJGv2LsySssLMkX1xCbmtLT0C49etaYvLO2HpI+qOBc/OSOjlMOAvgAHn16inT8EgjD8sW4JoDmZUERLrUdBnf0pqZle68LrZLGdNObPbQCKZFnPr+L3nsVKmoYCbxcay5WMCZjMUUykOdU3r/4QwA96bTX+WthZ8hMbuSqKuPZJYvJc7LC+RsMYDhPvgCnQfcTzuMuY216wDy+Lm+Nixo1obTLGPt7885WfEuVF4ShWEWu9EJbYBsay5z/qpXZC37aMMShNUv6fy5x2XrofkzbM51++5iZ/O74FEpGZJmXQP68VXDeiHDv7pY/DfzoxeN0rlmloxudVOOczMgnAF+2WksB6bz8GLAuz5imTAzD/0lhhHO50FRN4cwkvo/e0MklHwXQYaWKFM6Wbzw+n2rOExRTIHzevaIeodo1T7jtBx/5c+IBUw1sDJSv3BpI/1zsP7fhGig3iVz0BNcm56LBO3jrAhfWkWqDODNFJqCPPtLa6zW7hQJukxJeGJgafQ2GJA+T1teHVrFiiPQP8uPrdznm0krqclJPjWNF8H2Zd9vG29XIQ1LhDMrCQBlPJ2xTrQMubAvj0=
  secret_access_key:
    secure: EG1SKpG35W4Kcv0uAH9FIaLVuyzgstJKAqqyoDHPFBZEtTh3+Vwug9x26iUCDEGnr0HTpNqzaKUT2a6bSP6JELrfgKSUP2py99rMoXJJoeyd6IdlvgUlAXqBg4om4ptzq1T46yk24yIhRtwMUf2nTZTJq0Ojl5CgbkXRa0xXr3IfMnbKDKwlRdrf9wZ/FoFGw/CCav2OeheOX9sl2eHWIP/2weVJeHhEI66nvIXcXB7RwN2y2YnilXCuxFeIWA/CnzFKj8CnDzB4R7pn5bDMswYd9ISdIkwXRJB1xiVNlyZ/kMd4vMnzTa1SlgJhjF1I8ad8pQ2MxUrwL8QPodFjX97kq7FuodJMQ3lvK7S8hFduKZ3y0dUETXZ/A5jNhlYP84l96EmGy2rvhI4CYcBoxY7h236zUY/sc4eDrOkE06dfXnaMinLB6+vaKk6H4Tc5x7CqrhOlHqWKe8S5/rLymhmtCxjn+OA8UMD1+TqkV+4rxMKj3/hRtjGPIo70FncktgoH9Kpg9fuiPLL5/w2XnA051rbCpzktekuqb0oqxT+avDvq3xmDeje1cb2GXlI2m53ft7uUiM4gEq+eODh+2Zd3ZSVtnmmrUlMb7hDofOoHLiWmtcToDg6AUzYJ+z51/pDXoJ/3u0AMeTmOBrcbTl3jpUJjpx9hRMG6Ox+0ZQs=
  bucket: "bills.martincostello.com"
  region: eu-west-2
  skip_cleanup: true
  local_dir: build
  on:
    branch: deploy
