language: node_js
node_js: "node"

install:
  - npm install -g codecov
  - npm install

script:
  - npm run build
  - npm test -- --coverage
  - codecov

branches:
  only:
    - master
    - deploy

deploy:
  provider: s3
  access_key_id:
    secure: "gCyWMuM1ebHCwABe3RwkOBf3oKF5wSw0gMe62kd1BKRfTO6qqkiEBFBBzd4hHxY18LDwX8Xbmexw8rNTar/KQVI6SKPAEaQ5OcfLqH4z0ay+aOIkG4dl3vpXF+B+yae2eqF3E3EfdrhyIZhYafBymzfbchoN963TUDTlqwkuPBmMElZD+HwvhftNnXHf4h3tn8LN2x//gDPIE4seTBXujGa60TdMbbhBjaE17fgT5hvmpPu7/Air0OZr+Wb8tvfQ8txVhNaOPmqKYnFYyX6NXzbnl48qrrpmYjP/6whOMMkdVvlVCdhOV/hV9CnjNCVEPWu72KFn2OiX8o34XmJnJy1ict5MVEpP2p97uA9ms+/rQG/JkarpcCT4jHrws65AwLXOClAhn7N+hv70LT4uvl2ASBO4AkGT5a6oKv8mY2PeKTvCfHcSSXcJyFrJjYb7OAfXb2I1tl/kbVfETNkV9VXeZdlFQ51c6++MlASCFCuC0wnAygsWxhemcVw+cLlzvDR9gBlhjkRrgb4lH6WW/Tbfb6IaJiNVz3Fol4SJ7tK9B7Hbor29fTTSuzdg8QxJcvh9ILYtqJoXH/uy7v5DE48uxBeNZi8OlojA0jk3LiZBvVBa86NG+wuX00U/WAtGWlbU8Ofb1Yywx1OHmW/H48m53GNt/TtobrdJxMZrqJY="
  secret_access_key:
    secure: "Ar/dArP9/l72nMss4oGB+Pc4OUF10HNJwUmyfW7Lg6IjrIP0WQzLrDFo7MiAmAvCrYStAsoryE+BRtMqZZ3iXFsICuCp4e8BnPoYJbnU+CJXci+Aa+IopGrPEisiJB50SVZ01NOuW+Tu9a816D4ZnKEQJBGEzptup7F2hDoPFlCs32nff4kygPg7aDKE2PO6WJHNd1TAqUukBkjS/Wqtuwf+Q3q76WdlYvjGLSAuoy/HyhodsMLXSYfg0ePZMMMUVcNEJWptjdKgxFkUA+THV/yOgu2svJ/mK8akdmySlv97Vby0QrVh6KiozHQsnvoOjNqjEQol76bhL15yO2F+kyxl8OrKQfqlutm2hGv0co3O48YUKLE8zEXeQ9SIFIN97LKkV9KdeurDLdu3cYB0FvYgDW9jurdhtY8gjIMgwcU6gP7tf8QAt9rXDu0Wd26H9x5ITGDBamyyjs7iWV5AiS1NW1LsSdND7tLR/zcJtOitqUvhOwJ2+y+KNrlxqIFu1OzBbMRCwkOcX5Dd3KfYWwW3s9JYhEs9+hZKcnTD8gpg9Rjw6I3XS+PheWpyljzESnWhoRkgWrwPgg32PH6h0T6XoXNrqcgf7NXU/VgBFVsR/HpSgMpeFxV4uY2iPJ/4jc+RPl3cVzrSbXCG7fgVaoflr1g4tHA+I8jN8KRWWhA="
  bucket: "bills.martincostello.com"
  region: eu-west-2
  skip_cleanup: true
  local_dir: build
  on:
    branch: deploy
